version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_tracker
      - MYSQL_USER=nick
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
  app:
    image: spring-boot-project
    container_name: spring-boot-project
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/task_tracker?serverTimezone=UTC
    ports:
      - "8080:8080"
    depends_on:
      - mysql
